
AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'bin/*'
    - 'spec/**/*.rb'
    - 'tmp/**/*'
  UseCache: true
  MaxFilesInCache: 3000

Metrics/LineLength:
  Max: 110
  IgnoredPatterns: ['(\A|\s)#']

Metrics/BlockLength:
  Exclude:
    - 'kerosene.gemspec'
    - 'spec/**/*.rb'

Style/ExpandPathArguments:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false

AccessorMethodName:
  Enabled: false

AlignHash:
  EnforcedLastArgumentHashStyle: 'ignore_implicit'

Documentation:
  Enabled: false
