language: ruby
rvm: 2.5.3
cache:
  bundler: true
  yarn: true
sudo: required
before_install:
  - gem update --system
  - gem install bundler -v '< 2'
install: bundle install
addons:
  postgresql: '9.6'
script:
  - bundle exec rspec
