#!/bin/sh

# Set up Rails app. Run this script immediately after cloning the codebase.

# Exit if any subcommand fails
set -e

# Set up Ruby dependencies via Bundler
gem install bundler --conservative
bundle check || bundle install

# Install JavaScript dependencies
bin/yarn

# Set up database and add any development seed data
bundle exec rails db:create db:migrate db:seed
bundle exec rails db:test:prepare
